version: '3.7'

services:
  db:
    image: postgres:15
    networks:
      practica_net:
    env_file: .env
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - '5434:5434'
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./postgresql/init2.sql:/docker-entrypoint-initdb.d/init2.sql
      # - ./postgresql/init.dump:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB

  pgadmin:
    image: dpage/pgadmin4
    networks:
      practica_net:
    container_name: pgadmin4_container
    restart: always
    links:
      - db
    ports:
      - "8888:80"
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin-data:/var/lib/pgadmin

    command: ["./servidor.sh"]
  backend: 
    container_name: backend_container
    networks:
      practica_net:
    build:
      context: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_DB=$PG_DB
      - PG_PORT=$PG_PORT
      - PG_HOST=$PG_HOST
    depends_on:
      - db
      - pgadmin
    
  frontend:
    build: ./frontend
    networks:
      practica_net:
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    depends_on:
      - backend
    
  nginx:
    image: nginx:1.19.2-alpine
    networks:
      practica_net:
    container_name: loadbalancer-nginx
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - frontend

networks:
  practica_net:

volumes:
  local_pgdata:
  pgadmin-data:
  loadbalancer:
