# Generated by Django 5.0.1 on 2024-02-28 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_rent_id', models.CharField(null=True)),
                ('end_rent_id', models.CharField(null=True)),
                ('pay', models.CharField(max_length=25)),
                ('rent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_Billing', to='rent.rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Billing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
