# Generated by Django 5.0.1 on 2024-02-19 15:28

import stations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incidence_bici_alter_incidence_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='bici',
            field=models.CharField(null=True, verbose_name=stations.models.Bicis),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='station',
            field=models.CharField(null=True, verbose_name=stations.models.Stations),
        ),
    ]
