# Generated by Django 5.0.1 on 2024-02-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incidence_bici_alter_incidence_station'),
        ('stations', '0006_alter_bicis_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='bici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bici_affected', to='stations.bicis'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_affected', to='stations.stations'),
        ),
    ]
