# Generated by Django 3.2 on 2022-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('direction', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=200)),
                ('img', models.CharField(default='', max_length=255)),
                
            ],
        ),
    ]
