# Generated by Django 5.0.1 on 2024-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_remove_stations_slug_alter_stations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
