# Generated by Django 5.0.1 on 2024-01-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_stations_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('slot_number', models.IntegerField()),
                ('bici', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='stations.bicis')),
                ('stations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='stations.stations')),
            ],
        ),
    ]
