# Generated by Django 5.0.1 on 2024-01-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_bicis_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicis',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
