# Generated by Django 5.0.1 on 2024-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_alter_bicis_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='latitud',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stations',
            name='long',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
